[project]
name = "pythonfun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "logging>=0.4.9.6",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "web3>=7.11.0",
    "xlsxwriter>=3.2.5",
]
